### PR TITLE
update r-upsetr to version 1.4.0

### PR DESCRIPTION
**Pull request by dlaehnemann**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dbast** [comment]
@conda-forge-admin, please rerender

**Comment by dlaehnemann** [comment]
@conda-forge-admin please rerender

**Comment by dlaehnemann** [comment]
A local re-rendering on my own machine did the trick. @dbast, do you have the permissions to merge this, or could you recommend whom to ping, otherwise?

**Comment by dpryan79** [comment]
@conda-forge-admin please rerender

**Comment by dpryan79** [comment]
Weird, local conda-smithy does indeed work without issue (and says nothing needs to be changed). I'll merge given that.

**Comment by dlaehnemann** [comment]
Thanks for double-checking and for merging!

**Pull request merged**
